name: Railway Deploy
on:
    push:
        branches:
            - main
        paths-ignore:
            - "video-process-app/**"
            - README.md
defaults:
    run:
        working-directory: ./app
jobs:
    deploy:
        name: Deploy App
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - run: npm ci
            - run: npm i -g @railway/cli
            - name: Deploy
              run: railway up
              env:
                  RAILWAY_TOKEN: ${{ secrets.RAILWAY_APP_TOKEN }}
