name: Railway Deploy
on:
    push:
        branches:
            - main
        paths-ignore:
            - README.md
jobs:
    deploy_vp:
        name: Deploy Video Processing App
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - run: npm ci
              working-directory: ./video-process-app
            - run: npm i -g @railway/cli
            - name: Deploy
              run: railway up
              env:
                  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    deploy_app:
        name: Deploy App
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - run: npm ci
              working-directory: ./app
            - run: npm i -g @railway/cli
            - name: Deploy
              run: railway up
              env:
                  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
